<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Backup steps for mod_saylorcode.
 *
 * @package    mod_saylorcode
 * @copyright  2026 Saylor Academy
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

/**
 * Define the complete structure for backup, with user data where requested.
 *
 * @package    mod_saylorcode
 * @copyright  2026 Saylor Academy
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class backup_saylorcode_activity_structure_step extends backup_activity_structure_step {
    /**
     * Build the backup structure.
     *
     * @return backup_nested_element
     */
    protected function define_structure(): backup_nested_element {
        $userinfo = $this->get_setting_value('userinfo');

        // Every column on the table belongs here. The list is enumerated rather
        // than derived, so a column added later is silently dropped from every
        // backup until someone remembers this file: that is how startercode,
        // testcases, entryfilename and layout came to be missing, which would
        // have restored courses with the exercise content emptied out.
        // tests/backup_fields_test.php now fails if the two drift apart again.
        $saylorcode = new backup_nested_element('saylorcode', ['id'], [
            'name', 'intro', 'introformat', 'activitymode', 'stableid',
            'versionpolicy', 'pinnedversion', 'profileid', 'layout',
            'entryfilename', 'startercode', 'referencesolution', 'testcases',
            'maxattempts', 'gradingmode', 'allowhints', 'allowsolution',
            'allowdownload', 'grade', 'completionpasstests',
            'completionminscore', 'timecreated', 'timemodified',
        ]);

        $steps = new backup_nested_element('steps');
        $step = new backup_nested_element('step', ['id'], [
            'sectiontitle', 'sortorder', 'steptype', 'title', 'instructions',
            'instructionsformat', 'stableid', 'versionpolicy', 'pinnedversion',
            'carryforward', 'completionrule', 'allowrevisit', 'points',
            'timecreated', 'timemodified',
        ]);

        $attempts = new backup_nested_element('attempts');
        $attempt = new backup_nested_element('attempt', ['id'], [
            'userid', 'attemptnumber', 'status', 'currentstepid', 'score',
            'exerciseversion', 'timestarted', 'timemodified', 'timesubmitted',
            'timecompleted',
        ]);

        $stepattempts = new backup_nested_element('stepattempts');
        $stepattempt = new backup_nested_element('stepattempt', ['id'], [
            'stepid', 'status', 'latestsnapshotid', 'runcount', 'checkcount',
            'submitcount', 'hintsused', 'solutionviewed', 'bestscore',
            'latestscore', 'timefirstpassed', 'timecompleted', 'timemodified',
        ]);

        $snapshots = new backup_nested_element('snapshots');
        $snapshot = new backup_nested_element('snapshot', ['id'], [
            'stepid', 'snapshottype', 'files', 'label', 'timecreated', 'timeexpires',
        ]);

        // Build the tree.
        $saylorcode->add_child($steps);
        $steps->add_child($step);

        $saylorcode->add_child($attempts);
        $attempts->add_child($attempt);

        $attempt->add_child($stepattempts);
        $stepattempts->add_child($stepattempt);

        $attempt->add_child($snapshots);
        $snapshots->add_child($snapshot);

        // Data sources.
        $saylorcode->set_source_table('saylorcode', ['id' => backup::VAR_ACTIVITYID]);
        $step->set_source_table('saylorcode_steps', ['saylorcodeid' => backup::VAR_PARENTID], 'sortorder ASC');

        if ($userinfo) {
            $attempt->set_source_table('saylorcode_attempts', ['saylorcodeid' => backup::VAR_PARENTID]);
            $stepattempt->set_source_table('saylorcode_stepattempts', ['attemptid' => backup::VAR_PARENTID]);
            $snapshot->set_source_table('saylorcode_snapshots', ['attemptid' => backup::VAR_PARENTID]);
        }

        // Execution records are deliberately not backed up. They are
        // operational telemetry rather than student work, and they can be
        // regenerated by nothing, so restoring them would only carry stale
        // diagnostics into a new site.

        $attempt->annotate_ids('user', 'userid');
        $saylorcode->annotate_files('mod_saylorcode', 'intro', null);

        return $this->prepare_activity_structure($saylorcode);
    }
}
